#!/bin/sh
export DESKTOP_SESSION=thiny
xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
            -remove _NET_DESKTOP_NAMES \
            -remove _NET_CURRENT_DESKTOP 2> /dev/null

start-pulseaudio-x11
imsettings-switch -n -q -x

tint2 -c /usr/share/thiny-session/tint2rc &
guake &
nm-applet &
volumeicon &
batti &
sleep 5 && neap &

exec metacity --composite
