#!/bin/sh
export DESKTOP_SESSION=thiny
xprop -root -remove _NET_NUMBER_OF_DESKTOPS \
            -remove _NET_DESKTOP_NAMES \
            -remove _NET_CURRENT_DESKTOP 2> /dev/null

start-pulseaudio-x11
imsettings-switch -n -q -x

guake &
nm-applet &
volumeicon &
batti &
tint2 &
neap &

exec metacity
